allow zone transfers to nsi name servers
sapcc/helm-charts pull request #1889
Opened 2020-09-29 13:11 UTC by braunmatt

2020-09-29 15:09 UTC, galkindmitrii requested changes

2020-09-29 15:09 UTC, galkindmitrii commented on system/bind/templates/config.yaml
> +     include "/etc/bind/keys/nsi.key";
ConfigMap will be mounted into /etc/bind: https://github.com/sapcc/helm-charts/blob/master/system/bind/templates/deployment.yaml#L54-L55 , so path has to be changed

2020-09-30 15:01 UTC, braunmatt reviewed
correct path

2020-09-30 15:59 UTC, galkindmitrii approved these changes
lgtm

2020-10-01 09:51 UTC, merged