[nova] run nova-manage placement sync_aggregates in online-migration
sapcc/helm-charts pull request #1930
Opened 2020-10-08 11:34 UTC by mariusleu

2020-10-08 11:56 UTC, joker-official approved these changes

2020-10-09 06:51 UTC, joker-official requested changes
This should only run when we're on rocky. So we either need to get the version somehow (currently no idea - maybe some secrets value or from an image?) or we need to check for the availability of the command.

2020-10-09 10:24 UTC, joker-official commented on openstack/nova/templates/bin/_db-online-migrate.tpl
> +available_commands_text=$(nova-manage --help | awk '/Command categories/ {getline; print $0}')
Does `getline` read the next line?

2020-10-09 10:24 UTC, joker-official commented on openstack/nova/templates/bin/_db-online-migrate.tpl
> +if [[ $available_commands_text == *"placement"*  ]]; then
I don't feel like that's very accurate. Can we do something like
```
if echo "${available_commands_text}" | grep -q -E '[{,]placement[},]'; then
```
```
$ text='{version,bash-completion,network,cell_v2,db,cell,floating,api_db}'
$ echo "${text}" | grep -q -E '[{,]placement[},]' && echo "success"
$ text='{version,bash-completion,network,cell_v2,db,cell,floating,api_db,placement}'
$ echo "${text}" | grep -q -E '[{,]placement[},]' && echo "success"
success
```

Then we can also switch back to using `#!/bin/sh`.

2020-10-09 11:31 UTC, mariusleu commented on openstack/nova/templates/bin/_db-online-migrate.tpl
> +available_commands_text=$(nova-manage --help | awk '/Command categories/ {getline; print $0}')
Yes.

2020-10-09 11:49 UTC, joker-official approved these changes

2020-10-09 11:49 UTC, merged