creating statfullset templates
sapcc/helm-charts pull request #1947
Opened 2020-10-13 12:08 UTC by dhalimi

2020-10-13 13:26 UTC, kayrus requested changes
We have a CI job to check the changes, they are failing right now. In addition to save time, before pushing the changes try to test them locally.

2020-10-13 13:26 UTC, kayrus commented on openstack/cronus/values.yaml
> -  record: my-ingress.region.cloud.com
Can you move this back? The CI is failing because of this.

2020-10-13 13:26 UTC, kayrus commented on openstack/cronus/values.yaml
> -ingress-nginx:
Can you move this back too?

2020-10-26 22:45 UTC, dhalimi commented on openstack/cronus/templates/cronus/statefulset.yaml
> +              containerPort: {{ .Values.cronus.http }}
the statefulset file was merged with deployment and the path of the port was fixed in this file

2020-10-27 08:30 UTC, kayrus approved these changes
LGTM, thanks

2020-10-27 08:30 UTC, merged