[cinder] Migrate policy.json to policy.yaml
sapcc/helm-charts pull request #1966
Opened 2020-10-21 21:12 UTC by hemna

For cinder Queens and on, Cinder can use a policy.yaml file
instead of a policy.json file.  The policy.yaml is the default
for Rocky release and forward.

The rocky release notes describes the upgrade.
https://docs.openstack.org/releasenotes/cinder/rocky.html

2020-10-21 21:12 UTC, hemna commented
This patch is a pre-emptive migration for Train upgrade.

2020-10-22 14:48 UTC, joker-official reviewed
Did you manually compare the rules and copy over our stuff to yaml or how did you convert the file?

2020-10-22 15:55 UTC, hemna commented
As described in the release notes, the yaml file is basically. identical minus the wrapping {} around the json, and removing
of the , at the end of each line.   

So I basically did this:
cp policy.json policy.yaml
edit the file, removed the {} and , 

Then I generated the default cinder-policy.yaml.sample file from tox -egenpolicy
and compared the policy entries.  I changed some of the invalid policy entries that we had for
managing volume attachments, such as 
"volume:attach" : "...."  to the correct entry using the volume_extension actions.
I also added the group actions which are replacements for the old consistency group entries as CG's as an API don't exist anymore.

2020-10-22 16:18 UTC, joker-official requested changes

2020-10-22 16:18 UTC, joker-official commented on openstack/cinder/templates/etc/_cinder-policy.yaml.tpl
> +"default": "rule:context_is_admin"
Release-Notes state, that `default` is not used inside the code anymore, if I read this correctly.

2020-10-22 16:18 UTC, joker-official commented on openstack/cinder/templates/etc/_cinder-policy.yaml.tpl
> +"scheduler_extension:scheduler_stats:get_pools" : "rule:context_is_admin
This line is missing a closing `"`.

2020-10-22 16:18 UTC, joker-official commented
Nice explanation, thanks.

2020-10-23 08:11 UTC, joker-official commented on openstack/cinder/templates/etc/_cinder-policy.yaml.tpl
> +"group:list_replication_targets" :   "rule:context_is_admin"
hm ... I'm annoyed by those lines having a space before the `:`. We don't do it everywhere in the file. Can we straighten this out with a small run of `sed -r 's/" +:/":/' _cinder-policy.yaml.tpl`, please?

2020-10-26 13:59 UTC, joker-official approved these changes

2024-08-23 15:06 UTC, merged