bring back the resource types
sapcc/helm-charts pull request #1983
Opened 2020-10-29 15:12 UTC by BerndKue

2020-10-29 15:30 UTC, joker-official requested changes

2020-10-29 15:30 UTC, joker-official commented on openstack/ironic/templates/seed.yaml
> +      "resources:CUSTOM_ZG1BCM1_MEDIUM": "1"
This is the same as above. It shouldn't be, shouldn't it? There seems to be a `1` missing.

2020-10-29 15:30 UTC, joker-official commented on openstack/ironic/templates/seed.yaml
>        "capabilities:cpu_arch": "x86_64"
above, there's still one commented. why?

2020-10-29 16:14 UTC, BerndKue commented
Well spotted. Thanks for finding the two mistakes.

2020-10-30 07:52 UTC, joker-official approved these changes

2020-11-02 06:26 UTC, merged