[pvc_exporter] add alerts
sapcc/helm-charts pull request #2415
Opened 2021-04-16 08:02 UTC by rajivmucheli

Hi @galkindmitrii @defo89 

If this PR is acceptable, we need to create a playbook.

Regards,
Rajiv

2021-04-16 11:53 UTC, galkindmitrii commented
Looking good!
I think there are no playbooks for Info level alerts, or, are you planning to promote it to Warning later on?

2021-04-16 11:58 UTC, rajivmucheli commented
if alerting around 70% is acceptable then severity INFO is good, if its 90% then severity WARNING is preferable
.

2021-04-16 14:09 UTC, defo89 commented
Not sure if I am missing something, but I think current template will not deploy alerts. There should be a `PrometheusRule` that will pick up the the alerts defined in `alerts/pvc_usage.alerts` folder ([example](https://github.com/sapcc/helm-charts/blob/master/system/kube-proxy/templates/alerts.yaml)).

I think `info` severity is a good start. For other severities we need to think how and by whom the alerts should be actioned (playbook).

2021-04-16 14:59 UTC, auhlig commented
What @defo89 said^
Alerts are deployed via `PrometheusRule` CRD with label `prometheus: "kubernetes"` set in this case

2021-04-16 15:29 UTC, Carthaca requested changes

2021-04-16 15:32 UTC, Carthaca commented on prometheus-exporters/pvc-exporter/alerts/pvc_usage.alerts
> +      context: memory
maybe `space` or `storage`

2021-04-19 07:02 UTC, Carthaca reviewed
Thanks, I just have some small description suggestions

2021-04-21 13:45 UTC, defo89 approved these changes
lgtm

2021-04-21 13:53 UTC, Carthaca approved these changes
👍

2021-04-21 13:58 UTC, merged