system/gatekeeper: add GkHighCPURequest to prod ui
sapcc/helm-charts pull request #2862
Opened 2021-11-01 13:22 UTC by talal

2021-11-02 13:37 UTC, majewsky approved these changes
It seems you have found your way around Rego's unusual control flow quite aptly. Very nice, keep it up!

2021-11-02 13:42 UTC, majewsky requested changes
Oh wait, actually, there's one thing: We should only deploy this policy to the relevant clusters, e.g. to baremetal, but not to scaleout. I don't know for sure about the other clusters; can you check with Dmitri where it should be applied?

Then add a condition to the config object to only apply it in clusters with the right `.Values.cluster_type`. This value is given in the pipeline with `--set`, so we can rely on it being available.

2021-11-03 09:09 UTC, talal commented
Talked to Marian, he says we only need this in baremetal.

2021-11-03 09:11 UTC, majewsky approved these changes

2021-11-03 09:11 UTC, merged