Disable absent metric alert for apicequipments
sapcc/helm-charts pull request #2919
Opened 2021-11-18 10:48 UTC by artherd42

because we don't have these ACI devices in all regions

2021-11-18 11:01 UTC, IvoGoman requested changes
Maybe something like this so we only silence the alert in the regions where we do not expect the metric to be present?

2021-11-18 12:20 UTC, artherd42 commented on prometheus-exporters/apic-exporter/templates/alerts.yaml
> +    {{- if eq $path "alerts/apicequipments" }}
Make sense. I flipped through #alert-net-info channel and only qa-de-1 and ap-sa-2 constantly reports the metric missing.

2021-11-18 12:28 UTC, artherd42 commented on prometheus-exporters/apic-exporter/templates/alerts.yaml
> +    {{- end }}
```suggestion
    {{ - if or ( eq $values.globals.region "ap-sa-2" ) ( eq $values.globals.region "qa-de-1" ) }}
    absent-metrics-operator/disable: "true"
    {{- end }}
    {{- end }}
```

2021-11-19 13:52 UTC, IvoGoman approved these changes

2026-04-28 07:36 UTC, closed without merging