Use tier and service labels from Pod for KubernetesPodRestartingTooMuch
sapcc/helm-charts pull request #2923
Opened 2021-11-18 16:05 UTC by talal

I checked the helm template rendering using:

```sh
helm template --dry-run prometheus-kubernetes-rules ./prometheus-rules/prometheus-kubernetes-rules
```

and it gave the expected output:

```yaml
labels:
  tier: "{{ if $labels.label_tier }}{{ $labels.label_tier}}{{ else }}k8s{{ end }}"
  service: "{{ if $labels.label_service }}{{ $labels.label_service}}{{ else }}resources{{ end }}"
```

/cc @majewsky

2021-11-22 13:23 UTC, databus23 reviewed
Given that we will want to use this for more then a single alert. I would suggest to create a template helper.

So that this alert can be simplified to something like this:

```
labels:
  tier: {{ include "tierLabelOrDefault" .Values.tier }}
  service: {{ include "serviceLabelOrDefault" "resources" }}
```

2021-11-23 11:01 UTC, databus23 requested changes
In order to make the alert template as clean as possible I would not wrap the default value in a `dict`. I'm not seeing a benefit and the downside of more visual noise.

2021-11-23 13:15 UTC, databus23 approved these changes
LGTM. 👍

2021-11-23 13:16 UTC, majewsky approved these changes

2021-11-23 13:21 UTC, merged