[common][rabbitmq] use keppel alternate region for all rabbit container
sapcc/helm-charts pull request #3029
Opened 2022-01-10 20:29 UTC by galkindmitrii

images.

Alternate region is used in a similar way like for keystone or mariadb
charts. In case Keppel down in the region - the service won't be able to
start.

Also bump chart.

2022-01-12 12:45 UTC, Carthaca requested changes
I would prefer to have a switch like introduced for mariadb in 922f101559c1daacf5717e29fb1ffde341e8b5c3

some services may want to use the alternative region (e.g. keystone, swift, designate) to prevent a circular dependency for keppel, but other services probably not

2022-01-12 12:47 UTC, majewsky commented
I agree with Maurice. Usage of `AlternateRegion` should be restricted to the charts that need it. It is absolutely correct that Keystone and Designate use `AlternateRegion` to avoid a deadlock during regional cold-start, but for all other services, adding the DC interconnect to the alternate region as an additional deployment dependency is not really useful.

2022-01-17 09:49 UTC, Carthaca requested changes

2022-01-17 09:49 UTC, Carthaca commented on common/rabbitmq/templates/deployment.yaml
> +        image: {{include "dockerHubMirror" .}}/{{ .Values.image }}:{{.Values.imageTag }}"
uneven number of `"`

2022-01-17 09:49 UTC, Carthaca commented on openstack/designate/values.yaml
> +use_alternate_registry: true
This needs to go under the `rabbitmq` key(s)

2022-01-17 09:49 UTC, Carthaca commented on openstack/keystone/values.yaml
> +use_alternate_registry: true
same

2022-01-17 13:50 UTC, Carthaca approved these changes
lgtm

2022-01-17 14:02 UTC, merged