[netapp-exporter] add inode alerts for manila shares
sapcc/helm-charts pull request #3260
Opened 2022-03-23 15:46 UTC by chuan137

2022-03-23 16:25 UTC, Carthaca requested changes

2022-03-23 17:09 UTC, Carthaca approved these changes

2022-03-23 17:10 UTC, Carthaca commented
I suggest to wait with the rollout for the playbook

2022-03-25 23:00 UTC, geisslet commented on prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/alerts/netapp-capacity.alerts
> +      - alert: NetappVolumeInodeUsageVeryHigh
pls check the note on the [playbook of the critical](https://github.wdf.sap.corp/monsoon/convergedcloud-opsdocu-ui/pull/1152#pullrequestreview-6596826)

2022-05-04 11:09 UTC, Carthaca commented on prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/alerts/netapp-capacity.alerts
> +            severity: critical
let's set this down to `warning`, we have no proper 24/7 response for this anyway

2022-05-04 11:51 UTC, geisslet approved these changes
lgtm

2022-05-04 12:58 UTC, merged