[alertmanager] pagerduty network split by alert type
sapcc/helm-charts pull request #3526
Opened 2022-05-20 11:08 UTC by geisslet

there is a managed service split within tier net - this setup isn't final and the sequence hack is dirty, but necessary

2022-05-20 11:10 UTC, geisslet commented
vault and secret are adopted

2022-05-23 13:41 UTC, databus23 approved these changes

2022-05-23 13:47 UTC, databus23 requested changes
The `admin` region does not exist anymore for a long time and should be removed to reduce clutter by a few percent.

2022-05-23 13:58 UTC, databus23 approved these changes

2022-05-24 07:24 UTC, merged