[common/rabbitmq] Optimise startup script
sapcc/helm-charts pull request #3667
Opened 2022-06-23 12:25 UTC by fwiesel

Change the script to call rabbitmq less often

2022-06-23 15:38 UTC, bashar-alkhateeb reviewed
looks reasonable for me

2022-06-23 16:17 UTC, fwiesel commented
It certainly sends `SIGTERM`, but to my knowledge that triggers the `EXIT` handler in bash (not in other shells though).

2022-06-24 07:29 UTC, notandy requested changes
~~I assume the designate change is not intended~~
It seems the github client is broken and shows deprecated changes, sorry

2022-06-24 08:48 UTC, notandy approved these changes

2022-06-27 07:05 UTC, merged