Promoting the SDRS alert to Warning /Critical
sapcc/helm-charts pull request #4147
Opened 2022-10-17 16:47 UTC by rezash84

Promoting the SDRS alert to Warning /Critical status and removed the info alert .

2022-10-18 06:50 UTC, christopherhans commented
Did you encountered the alert already and used the linked playbook?

2022-10-18 07:32 UTC, christopherhans requested changes

2022-10-18 07:32 UTC, christopherhans commented on prometheus-exporters/vrops-exporter/alerts/datastore.alerts
>        tier: vmware
```suggestion
      tier: vmware
      support_group: compute
```

2022-10-18 07:32 UTC, christopherhans commented on prometheus-exporters/vrops-exporter/alerts/datastore.alerts
>        tier: vmware
There is a new label for the upcoming target operation model.

2022-10-18 07:32 UTC, christopherhans commented on prometheus-exporters/vrops-exporter/alerts/datastore.alerts
> +      tier: vmware
```suggestion
      tier: vmware
      support_group: compute
```

2022-10-18 20:26 UTC, rezash84 commented
Playbook have been created and reviewed  for this alert  covers both Warning and Critical alert instances  and this is to replace the old EPH datastore capacity alerts we have in place currently.
Moreover , the SDRS alert have been in observation period for 3 weeks to ensure correct functionality .
Please review and advise .
Thanks

2022-10-19 09:10 UTC, christopherhans commented
@artherd42 asking for your feedback if this alert can be rolled out directly from info to warning&critical.
See Rezas comment above.

2022-10-26 15:25 UTC, artherd42 commented
@rezash84 Did you see false-positive alerts during the 3 observation weeks? And got these alerts fixed? Did the ops team has accepted the new alert?

2022-10-26 16:27 UTC, rezash84 commented
Hi @artherd42 , yes we have fixed  issue related to the alert during observation period and the Ops team has accepted the new alerts as well .Thank you!

2022-10-27 07:06 UTC, artherd42 approved these changes
lgtm

2022-11-01 14:17 UTC, merged