Introducing vmware-monitoring
sapcc/helm-charts pull request #4300
Opened 2022-11-08 15:53 UTC by richardtief

Merge `vrops-exporter` and `prometheus-vmware` to create resources for multiple monitoring targets. 

The chart requires the newly implemented dependency prometheus-server 7.1.0 and thanos 0.2.0, which are capable of creating multiple resources. 

vrops-exporter alerts are still deployed with this chart. They will be moved to a separate chart in the future.

2022-11-08 16:00 UTC, richardtief commented
The validation error is intentional. The dependencies must be merged first. 
`Error: can't get a valid version for repositories prometheus-server, thanos.`

2022-11-11 12:12 UTC, viennaa requested changes
Thanks for finishing up, only some minor things.

2022-11-11 12:12 UTC, viennaa commented on system/vmware-monitoring/values.yaml
> +    size: 100Gi
```suggestion
    size: 10Gi
```

This is the metal variant, let's see where we go here. If we go to scaleout, we need to adjust anyway.

2022-11-11 12:12 UTC, viennaa commented on system/vmware-monitoring/values.yaml
> +  retentionTime: 4h
```suggestion
  retentionTime: 7d
```

2022-11-30 09:09 UTC, merged