[nova] Update policy for system-scoped endpoints
sapcc/helm-charts pull request #4323
Opened 2022-11-11 13:29 UTC by joker-at-work

System-scoped endpoints got their "target" dict set to an empty dict which made our previous way to write the policy break. Instead of having only "rule:owner", we now also allow "rule:projectless" for view, member and admin rules. This makes sure that these roles are also allowed to use non-project endpoints e.g. listing availability zones where the target is empty.

Previously, those endpoints did not set an explicit target and thus got
the default: the token's project_id.

2022-11-11 13:30 UTC, joker-at-work commented
requires https://github.com/sapcc/nova/pull/373

2022-11-11 14:42 UTC, grandchild requested changes
I'd merge the `projectless` thing into `owner` and rename that. `owner` is only used in the admin/member/viewer rules.

The commit message doesn't really explain it well for me:

```diff
-got their "target" dict set to an empty dict which made our previous
-way to write the policy break.
+got their "target" dict (containing user and project ID) set to an
+empty dict, i.e. missing the project_id required for the `rule:owner`
+check which made our policy fail.
```

```diff
-Instead of having only "rule:owner", we now also allow "rule:projectless"
-for view, member and admin rules.
+Instead of matching only on project_id which might now be missing, we
+also explicitly allow requests without project_id for view, member and
+admin rules.
```


```diff
-and thus got the default: the token's project_id.
+and thus got the default: the token's project_id, which made the rule pass.
```

2022-11-11 14:42 UTC, grandchild commented on openstack/nova/templates/etc/_nova-policy.yaml.tpl
>  owner: project_id:%(project_id)s
```suggestion
owner_or_no_project: project_id:%(project_id)s or ccloud_no_project_id_in_target:True
```

2022-11-11 14:42 UTC, grandchild commented on openstack/nova/templates/etc/_nova-policy.yaml.tpl
> +admin: (role:compute_admin or role:compute_admin_wsg) and ( rule:owner or rule:projectless )
```suggestion
member: role:member and rule:owner_or_no_project
viewer: role:compute_viewer and rule:owner_or_no_project
admin: (role:compute_admin or role:compute_admin_wsg) and rule:owner_or_no_project
```

2022-11-14 09:27 UTC, grandchild approved these changes

2022-11-14 09:28 UTC, merged

2022-11-14 09:28 UTC, joker-at-work commented
This PR had my approval, too :)