Add Hda domain in services seeds
sapcc/helm-charts pull request #4340
Opened 2022-11-15 10:23 UTC by rajivmucheli

2022-11-21 07:19 UTC, Carthaca requested changes
Additionally to the inline comments, I would like it better, if the new seeds would be placed alphabetically, i.e. not between 'fsn' and 'hcm', but between 'hcp03' and 'hec'.
But this is just cosmetics in the end

2022-11-21 07:19 UTC, Carthaca commented on openstack/keppel/templates/seed.yaml
> +{{- $domains := list "cc3test" "bs" "cis" "cp" "fsn" "hc" "hcm" "hcp03" "hec" "monsoon3" "neo" "s4" "wbs" }}
should add `hda`

2022-11-21 07:19 UTC, Carthaca commented on openstack/limes/templates/seed.yaml
> +{{- $domains := list "bs" "cc3test" "cp" "cis" "fsn" "hc" "hcm" "hcp03" "hec" "monsoon3" "neo" "s4" "wbs" -}}
should add `hda`

2022-11-21 07:45 UTC, Carthaca approved these changes

2022-11-21 09:12 UTC, majewsky approved these changes

2022-11-21 10:11 UTC, joker-at-work approved these changes

2022-11-21 10:18 UTC, galkindmitrii approved these changes

2022-11-24 12:52 UTC, merged

2022-11-24 13:24 UTC, majewsky commented
Limes and Keppel rolled out.

2022-11-24 13:45 UTC, Carthaca commented
Manila rolled out