common prometheus-pre7: support_groups and service added on alerts
sapcc/helm-charts pull request #4391
Opened 2022-11-28 13:30 UTC by richardtief

Prerequisite for onboarding the global prometheus to the new operating model. The same applies to the Maia prometheus, with special routing now possible.

2022-11-29 16:16 UTC, viennaa reviewed
Thanks for preparing the move. Two little questions from my side.

2022-11-29 16:16 UTC, viennaa commented on common/prometheus-server-pre7/templates/alerts/_prometheus.alerts.tpl
> +      meta: 'Prometheus `{{`{{ $labels.prometheus }}`}}` failed to load it`s configuration.'
Why do we need to double tick this?

2022-11-29 16:23 UTC, richardtief commented on common/prometheus-server-pre7/templates/alerts/prometheus-alerts.yaml
> +    prometheus: {{ default (include "prometheus.name" .) .Values.alerts.prometheus }}
For Maia, we can set `prometheus-openstack` to pick up the metrics from Maia Prometheus and Thanos. This way we can remove the Alertmanger from Maia Prometheus again.

2022-11-29 16:39 UTC, viennaa requested changes
Little typo fix

2022-11-30 07:48 UTC, viennaa approved these changes
I like it, let's go.

2022-11-30 07:49 UTC, merged