[neutron] Optional Log-shipping for dnsmasq
sapcc/helm-charts pull request #4411
Opened 2022-12-01 18:31 UTC by fwiesel

It depends on the image build from
https://github.com/sapcc/dnsmasq-log-exporter
which prints and rotates the logs from dnsmasq
and prefixes the logs with the network-id

2022-12-01 20:44 UTC, notandy requested changes
If you like this for QA/development - I am fine. But it way too blown for production - I'am already not happy with 3 containers per network pod. I neither see any tests for your software nor a build pipeline.

2022-12-02 08:22 UTC, fwiesel commented
> If you like this for QA/development - I am fine. But it way too blown for production

We currently observe in production dnsmasq becoming non-responsive on tcp ports, and since the logs are send to /dev/null, we have zero visibility.
So, you think it is better to not get any error logs in production in order to avoid a container?

>  I neither see any tests for your software nor a build pipeline.

I am not to do any test or pipeline before there is some buy-in. Maybe someone has a better proposal. But I can't find any tool doing that for us.

2022-12-02 08:44 UTC, fwiesel commented
I see following options:
1. Run dnsmasq with --no-daemon (Which has the comment "run in debug mode" in the help) and change the code in neutron to handle a non-forking process. Question there is how to get the network uuid into the log output.
2. Get the nodes logs into ELK  at least for dnsmasq. It logs to syslog, and the container has the nodes /dev/log device mounted, so it seems that was the intend, but I can't find any logs in ELK. Maybe we just to fix this.
3. Log to files, ship & rotate them as in this proposal.

2022-12-02 08:54 UTC, joker-at-work commented
Imho 1. doesn't work easily, because `dnsmasq` is started (afaics) via the `neutron-rootwrap-daemon` which also daemonizes itself and thus closes stdout.

I agree with Andy, that we don't want detailed DNS and DHCP logs as that would overwhelm our log-storage in production.

2022-12-02 09:28 UTC, fwiesel commented
> Imho 1. doesn't work easily,

Yes, I agree it is not easily done. It was the first thing I looked at. Can it be easily logged to stdout? In my opinion, the changes are much more effort than (3).  It would though address the number of containers.

> I agree with Andy, that we don't want detailed DNS and DHCP logs as that would overwhelm our log-storage in production.

Andy is arguing the number of containers, there was no mention of amount of logs.

DNS is not logged by dnsmasq, unless explicitly enabled with `log-queries` (as done in qa)
DHCP and other logs can be disabled by the options `--quiet-dhcp, --quiet-dhcp6, --quiet-ra, --quiet-tftp`.

From the manual:
> Suppress logging of the routine operation of these protocols. Errors and problems will still be logged.

I've added them as default to address your concern. We probably want to override them in qa though, should be proceed with this.

2022-12-02 10:00 UTC, joker-at-work commented
Sorry, I interpreted the

> But it way too blown for production 

as meaning logs.


> DNS is not logged by dnsmasq, unless explicitly enabled with log-queries (as done in qa)

Setting `dnsmasq_base_log_dir` will [set `--log-queries`](https://github.com/sapcc/neutron/blob/40f87abeeffca36786f82fcf3628898a6c6165bb/neutron/agent/linux/dhcp.py#L504) afaics. What am I missing here?

>  --quiet-dhcp and quiet-dhcp6 are over-ridden by --log-dhcp.

according to the manpage. `--log-dhcp` is set when `dnsmasq_base_log_dir` is set, too.

I'd prefer option 2, because then we could also get logs from the rootwrap-daemon (which supports syslog and which swalled problems for us before).

Regarding option 1, the `--no-daemon` documentation states

> to stop dnsmasq daemonising in production, use --keep-in-foreground

So there is a way to do foreground without also getting all the debugging enabled.

2022-12-02 10:40 UTC, fwiesel commented
> Setting `dnsmasq_base_log_dir` will [set --log-queries](https://github.com/sapcc/neutron/blob/40f87abeeffca36786f82fcf3628898a6c6165bb/neutron/agent/linux/dhcp.py#L504) afaics. What am I missing here?

Ah, no. I missed that. Should we go this way, that needs to be adjusted (either made configurable, or removed, since we configure it already through the config file)

> I'd prefer option 2, because then we could also get logs from the rootwrap-daemon (which supports syslog and which swalled problems for us before).

I am not against syslog/journald, quite the contrary, but I had trouble seeing how to transport the network-id through.

I looked into it,  and since the command is part of the record, and the uuid is passed in the command, it can be extracted by the equivalent of:
```
journalctl _EXE=/usr/sbin/dnsmasq -o json-pretty --since '10m ago' --output-fields="_CMDLINE,MESSAGE" \
  | jq -r  '"\(._CMDLINE[65:100]): \(.MESSAGE)"'
```

I'll check with the colleagues if they see a problem shipping those logs to ELK.

2022-12-02 10:51 UTC, joker-at-work commented
Until then, maybe we can use your way of shipping logs in a small qa region and see if we can reproduce the problem from production there.

2022-12-02 11:12 UTC, businessbean commented
> > Setting `dnsmasq_base_log_dir` will [set --log-queries](https://github.com/sapcc/neutron/blob/40f87abeeffca36786f82fcf3628898a6c6165bb/neutron/agent/linux/dhcp.py#L504) afaics. What am I missing here?
> 
> Ah, no. I missed that. Should we go this way, that needs to be adjusted (either made configurable, or removed, since we configure it already through the config file)
> 
> > I'd prefer option 2, because then we could also get logs from the rootwrap-daemon (which supports syslog and which swalled problems for us before).
> 
> I am not against syslog/journald, quite the contrary, but I had trouble seeing how to transport the network-id through.
> 
> I looked into it, and since the command is part of the record, and the uuid is passed in the command, it can be extracted by the equivalent of:
> 
> ```
> journalctl _EXE=/usr/sbin/dnsmasq -o json-pretty --since '10m ago' --output-fields="_CMDLINE,MESSAGE" \
>   | jq -r  '"\(._CMDLINE[65:100]): \(.MESSAGE)"'
> ```
> 
> I'll check with the colleagues if they see a problem shipping those logs to ELK.



> > Setting `dnsmasq_base_log_dir` will [set --log-queries](https://github.com/sapcc/neutron/blob/40f87abeeffca36786f82fcf3628898a6c6165bb/neutron/agent/linux/dhcp.py#L504) afaics. What am I missing here?
> 
> Ah, no. I missed that. Should we go this way, that needs to be adjusted (either made configurable, or removed, since we configure it already through the config file)
> 
> > I'd prefer option 2, because then we could also get logs from the rootwrap-daemon (which supports syslog and which swalled problems for us before).
> 
> I am not against syslog/journald, quite the contrary, but I had trouble seeing how to transport the network-id through.
> 
> I looked into it, and since the command is part of the record, and the uuid is passed in the command, it can be extracted by the equivalent of:
> 
> ```
> journalctl _EXE=/usr/sbin/dnsmasq -o json-pretty --since '10m ago' --output-fields="_CMDLINE,MESSAGE" \
>   | jq -r  '"\(._CMDLINE[65:100]): \(.MESSAGE)"'
> ```
> 
> I'll check with the colleagues if they see a problem shipping those logs to ELK.

[Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-journald.html) can directly fetch journald logs. Lets check if fluentd can do the same...

2022-12-02 11:15 UTC, businessbean commented
> > > Setting `dnsmasq_base_log_dir` will [set --log-queries](https://github.com/sapcc/neutron/blob/40f87abeeffca36786f82fcf3628898a6c6165bb/neutron/agent/linux/dhcp.py#L504) afaics. What am I missing here?
> > 
> > 
> > Ah, no. I missed that. Should we go this way, that needs to be adjusted (either made configurable, or removed, since we configure it already through the config file)
> > > I'd prefer option 2, because then we could also get logs from the rootwrap-daemon (which supports syslog and which swalled problems for us before).
> > 
> > 
> > I am not against syslog/journald, quite the contrary, but I had trouble seeing how to transport the network-id through.
> > I looked into it, and since the command is part of the record, and the uuid is passed in the command, it can be extracted by the equivalent of:
> > ```
> > journalctl _EXE=/usr/sbin/dnsmasq -o json-pretty --since '10m ago' --output-fields="_CMDLINE,MESSAGE" \
> >   | jq -r  '"\(._CMDLINE[65:100]): \(.MESSAGE)"'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'll check with the colleagues if they see a problem shipping those logs to ELK.
> 
> > > Setting `dnsmasq_base_log_dir` will [set --log-queries](https://github.com/sapcc/neutron/blob/40f87abeeffca36786f82fcf3628898a6c6165bb/neutron/agent/linux/dhcp.py#L504) afaics. What am I missing here?
> > 
> > 
> > Ah, no. I missed that. Should we go this way, that needs to be adjusted (either made configurable, or removed, since we configure it already through the config file)
> > > I'd prefer option 2, because then we could also get logs from the rootwrap-daemon (which supports syslog and which swalled problems for us before).
> > 
> > 
> > I am not against syslog/journald, quite the contrary, but I had trouble seeing how to transport the network-id through.
> > I looked into it, and since the command is part of the record, and the uuid is passed in the command, it can be extracted by the equivalent of:
> > ```
> > journalctl _EXE=/usr/sbin/dnsmasq -o json-pretty --since '10m ago' --output-fields="_CMDLINE,MESSAGE" \
> >   | jq -r  '"\(._CMDLINE[65:100]): \(.MESSAGE)"'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'll check with the colleagues if they see a problem shipping those logs to ELK.
> 
> [Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-journald.html) can directly fetch journald logs. Lets check if fluentd can do the same...

Fluentd can do the same with a [3rd party plugin](https://github.com/fluent-plugin-systemd/fluent-plugin-systemd) but not [natively](https://docs.fluentd.org/input#list-of-input-plugins)

2022-12-02 13:49 UTC, notandy commented
> So, you think it is better to not get any error logs in production in order to avoid a container?

I didn't said that - stop implying. This PR has no chance of merging in it's current form.

2022-12-02 14:24 UTC, fwiesel commented
> > So, you think it is better to not get any error logs in production in order to avoid a container?

> I didn't said that - stop implying.

I am saying it to make clear what the implication is. And the temporal aspect is here an important one:
As long as we do not have any solution in place, we practically do not have any logs to investigate the problem in production. I thought this was a quick and possibly dirty way to do that.

> This PR has no chance of merging in it's current form.

Fine by me. I have no vested interest in that particular solution. 
I made this and other proposals, if you do not see any urgency in getting a handle at fixing the problem in production then we leave it at that.

2022-12-02 14:24 UTC, closed without merging