[PX] Deploy podmonitor with each domain, per domain
sapcc/helm-charts pull request #4642
Opened 2023-02-13 17:42 UTC by swagner-de

Carve the podmonitor again out of the bird.yaml file and deploy it for every domain found usning loops to find out which domains exists. Previous chart did not deploy the podmonitor at all, since it was in a conditional that requires pxmon to be present.

2023-02-13 18:54 UTC, rhalina approved these changes

2023-02-14 08:25 UTC, richardtief requested changes

2023-02-14 08:25 UTC, richardtief commented on px/bird/templates/podmonitor.yaml
> +  namespace: infra-collector
namespace`infra-collector` doesn't exist. You can leave it at `px`.

2023-02-14 10:38 UTC, richardtief approved these changes

2023-02-14 10:42 UTC, merged