[prometheus-server] adding sidecar discovery
sapcc/helm-charts pull request #4708
Opened 2023-02-28 15:06 UTC by viennaa

2023-02-28 15:12 UTC, richardtief requested changes
Thanks for this additional feature. One litte remark.

2023-02-28 15:12 UTC, richardtief commented on common/prometheus-server/templates/thanos/storeendpoint.yaml
> +  url: {{ include "prometheus.name" (list $name $root) }}.{{ $thanos.namespace }}.svc.kubernetes.{{- required ".Values.global.region missing" $root.Values.global.region -}}.{{- required ".Values.glob
Please add the default cluster domain as well: `cluster.local`. Or make it customisable via values.

2023-02-28 15:14 UTC, richardtief commented on common/prometheus-server/templates/thanos/storeendpoint.yaml
> +  url: {{ include "prometheus.name" (list $name $root) }}.{{ $thanos.namespace }}.svc.kubernetes.{{- required ".Values.global.region missing" $root.Values.global.region -}}.{{- required ".Values.glob
We can also use this pattern w/o port:
`dnssrvnoa+_grpc._tcp.{{ include "prometheus.name" (list $name $root) }}.{{ $thanos.namespace }}.svc.{{ .Values.clusterDomain }}`

2023-02-28 15:55 UTC, richardtief requested changes

2023-03-01 07:58 UTC, viennaa commented on common/prometheus-server/templates/thanos/storeendpoint.yaml
> +  url: {{ include "prometheus.name" (list $name $root) }}.{{ $thanos.namespace }}.svc.kubernetes.{{- required ".Values.global.region missing" $root.Values.global.region -}}.{{- required ".Values.glob
we go with cluster.local.
Readme updated accordingly

2023-03-01 08:09 UTC, richardtief approved these changes
Thanks! Looks good.

2023-03-01 08:11 UTC, merged