[alertmanager] Add k8s email receiver config
sapcc/helm-charts pull request #4912
Opened 2023-05-11 12:41 UTC by uwe-mayer

2023-05-16 15:24 UTC, bassel-z requested changes
Thanks for the PR. Please see comments

2023-05-17 06:53 UTC, uwe-mayer commented on global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
> +    - to: {{"'{{ .CommonLabels.primary_contact_email }}'"}}
fixed by a more generic approach for an e-mail receiver

2023-05-17 06:53 UTC, uwe-mayer commented on global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
> +    - to: {{ .Values.email_k8s_alerting.email_bcc_to_address }}
Thanks for the input, I now opted for a more generic approach to the e-mail receiver making use of the `to` envelope and the headers as suggested

2023-05-17 14:19 UTC, bassel-z approved these changes
LGTM

2023-05-19 07:09 UTC, merged