[openstack/utils] Topology refinement
sapcc/helm-charts pull request #4989
Opened 2023-05-30 14:48 UTC by fwiesel

- Use default instead of value as the default value from global is not properly merged
- Add service annotations for topology aware routing
- Add the annotations only in regions with more than one az

2023-05-30 14:50 UTC, fwiesel commented
Follow up to #4965

2023-05-31 06:34 UTC, Carthaca commented
With removing the `.global.topology_key`value, can you please also rework `kubernetes_pod_az_affinity`? 
I noticed, that the `.Values` are anyhow not working in https://github.com/sapcc/helm-charts/pull/4965/files#diff-a8000139f34581224d5ac4276723eb108ae9879555d815bbe05577f0076d4534R35, the input to the function is only a availability zone name

2023-05-31 07:53 UTC, fwiesel commented
Done: I've renamed it to `utils.kubernetes_pod_az_affinity`, and pass it `envAll`. I'll need then to update the charts using it when making use of it.

2023-06-01 07:29 UTC, Carthaca requested changes
Thanks, a tiny extra letter sneaked in :)

2023-06-01 07:29 UTC, Carthaca commented on openstack/utils/templates/_affinity.tpl
> +s
This `s` comes probably unintended

2023-06-01 07:35 UTC, fwiesel commented on openstack/utils/templates/_affinity.tpl
> +s
Sorry, indeed. I've removed it.

2023-06-01 08:21 UTC, Carthaca approved these changes
Thanks!

2023-06-01 08:22 UTC, merged