[alert] pod resource usage alerts added
sapcc/helm-charts pull request #5130
Opened 2023-06-27 14:28 UTC by businessbean

- to detect containers with lower or higher than requested RAM usage
- to detect pods that have no CPU or RAM requests configured

2023-06-28 09:46 UTC, businessbean commented on prometheus-rules/prometheus-kubernetes-rules/alerts/pod.alerts.tpl
> +      playbook: docs/support/playbook/kubernetes/k8s_container_pod_low_ram_usage
Yes, if we use anchor links. I want to avoid that you have to read the complete document...

2023-06-28 09:48 UTC, businessbean commented on prometheus-rules/prometheus-kubernetes-rules/alerts/pod.alerts.tpl
> +    expr: floor(sum(container_memory_working_set_bytes{pod!=""}) BY (namespace, pod, container) / ON (namespace, pod, container) sum(kube_pod_container_resource_requests_memory_bytes > 0) BY (namespa
> Why do we need the sum and >0
To safeguard from a division by zero error. 

> Maybe we can also set 20 or 30 percent 
I want to start with quite low and quite high values to limit the amount of alerts in the beginning. Later we can tweak it...

2023-06-28 11:32 UTC, richardtief approved these changes
Approved from the monitoring point of view. Please ensure that the support teams are not overwhelmed with alerts.

2023-06-28 11:58 UTC, richardtief requested changes
Just forgot: Please bump the chart to reflect the changes.  
https://github.com/sapcc/helm-charts/blob/3a34e679948ce0daa54bd92a8cf3dc5ff1925a28/prometheus-rules/prometheus-kubernetes-rules/Chart.yaml#L5

2023-06-28 12:38 UTC, businessbean commented
> Just forgot: Please bump the chart to reflect the changes.
> 
> https://github.com/sapcc/helm-charts/blob/3a34e679948ce0daa54bd92a8cf3dc5ff1925a28/prometheus-rules/prometheus-kubernetes-rules/Chart.yaml#L5

`1.6.2` or `1.7.0`?

2023-06-28 12:49 UTC, richardtief commented
> `1.6.2` or `1.7.0`?

`1.7.0`

2023-06-29 08:06 UTC, Nuckal777 approved these changes

2023-07-04 08:28 UTC, richardtief approved these changes

2023-07-04 08:30 UTC, merged