[manila-nanny] add nanny for checking affinity
sapcc/helm-charts pull request #5256
Opened 2023-08-10 08:41 UTC by chuan137

2023-08-10 08:52 UTC, Carthaca requested changes
Good morning, Mister copy&paste ;)

2023-08-10 08:52 UTC, Carthaca commented on openstack/manila-nanny/templates/deployment.yaml
> +              value: {{ .Values.nannies.snapshot_missing.prometheus_port | quote }}
```suggestion
              value: {{ .Values.nannies.affinity.prometheus_port | quote }}
```

2023-08-10 08:52 UTC, Carthaca commented on openstack/manila-nanny/templates/deployment.yaml
> +            {{- .Values.nannies.snapshot.resources | default .Values.resources | toYaml | nindent 12 }}
```suggestion
            {{- .Values.nannies.affinity.resources | default .Values.resources | toYaml | nindent 12 }}
```

2023-08-10 08:52 UTC, Carthaca commented on openstack/manila-nanny/templates/deployment.yaml
> +          {{ include "promPort" .Values.nannies.snapshot | nindent 10 | trim }}
```suggestion
          {{ include "promPort" .Values.nannies.affinity | nindent 10 | trim }}
```

2023-08-10 08:52 UTC, Carthaca commented on openstack/manila-nanny/values.yaml
> +    prometheus_port: 9505
```suggestion
    prometheus_port: 9506
```

2023-08-10 14:39 UTC, chuan137 commented
> Good morning, Mister copy&paste ;)

😓

2023-08-11 06:08 UTC, chuan137 commented
add aggregation rules and alerts
playbook is added here https://github.wdf.sap.corp/cc/documentation-operation/pull/1907/files

2023-08-11 07:02 UTC, Carthaca approved these changes

2023-08-11 07:44 UTC, merged