[WIP][manila] add antelope chart
sapcc/helm-charts pull request #5485
Opened 2023-10-20 15:47 UTC by Carthaca

Can be installed in parallel to the manila chart.
Most of the things are separated by the name, some got new
switches visible in openstack/manila-antelope/values.yaml

2023-10-20 15:48 UTC, Carthaca commented on openstack/manila-antelope/values.yaml
> +  enabled: false
needs a better name - since the endpoints are still seeded, but nothing else

2023-10-20 15:49 UTC, Carthaca commented on openstack/manila-antelope/Chart.yaml
> +    repository: file://../manila
will be adjusted

2023-10-20 15:49 UTC, Carthaca commented on openstack/manila/Chart.lock
> +  repository: file://../utils
will be adjusted, waiting for https://github.com/sapcc/helm-charts/pull/5484

2023-10-24 14:30 UTC, chuan137 requested changes
Thanks for working on this. Only one thing, the coordinate pvc name is defined using Chart name. So is the mount file name. Maybe changing the util function can quickly fix it

2023-10-24 14:54 UTC, Carthaca commented
I already implemented https://github.com/sapcc/helm-charts/commit/a4fa85952f77cd9c48386af4b867718e510c63ce to fix the mount path.

And I'm okay with having a new pvc for coordination - were you thinking of re-using the existing one for antelope then?

2023-10-24 15:07 UTC, chuan137 commented
reuse the pvc is fine for me, but then it should not be deployed twice

2023-10-24 15:09 UTC, Carthaca commented
No, here nothing will change and in the antelope installation it will be set https://github.com/sapcc/helm-charts/pull/5498/files#diff-b4405cb045726a33d9d8d6321aaadec7de545581a2a559d79e8bdc7ee72aedc3R4

2023-10-24 15:10 UTC, Carthaca commented
I think re-using is more complex - and since we plan to do this in qa only not worth the effort

2023-10-24 15:25 UTC, Carthaca commented
No, defined here https://github.com/sapcc/helm-charts/blob/27f1ae247eff35093e32b917f557166eea526118/openstack/utils/templates/_coordination.tpl#L2

it contains the Chart name which will be different

2023-10-24 15:34 UTC, chuan137 commented
hmm, does it work as expected? the resource is defined in manila chart, what is the chart name  when the yaml file is parsed? manila or manila-antelope. I am not very sure

2023-10-24 15:35 UTC, chuan137 approved these changes

2023-10-24 15:39 UTC, Carthaca commented
according to helm template it works 🙂

2023-10-24 15:40 UTC, merged