[octavia] Add labels project/AZ for AZ-aware LB usage reporting
sapcc/helm-charts pull request #5671
Opened 2023-11-28 13:56 UTC by BenjaminLudwigSAP

This PR is for AZ-aware LB usage reporting with Limes. Limes will probably want to `sum by (loadbalancer_availabilityzone)` or something and set label `loadbalancer_status!="DELETED"`.

Neutron added a dedicated metric for this in #5374, but the already existing `octavia_loadbalancers_count_gauge` should work fine, since our Grafana/Plutono dashboards all use this metric with `sum()`. The only place that has to be changed is the `OpenstackOctaviaLoadbalancerErrored` alert, see below.

---

Also:

- Fix `OpenstackOctaviaLoadbalancerErrored` alert: Since `octavia_loadbalancers_count_gauge` is labelled by status and host (and now also project and AZ), `rate()` will calculate the rate of `ERROR` LB count per status and host (and project and AZ), but we are interested in the *overall* `ERROR` LB count.

- `values.yaml`: Remove trailing whitespace

---

Belongs to CCC-34464

2023-11-28 14:41 UTC, majewsky approved these changes

2023-11-28 15:20 UTC, majewsky requested changes
I just noticed that usage is only half of what we need. We also need to have the capacity broken down by AZ.

We are currently computing capacity by counting octavia-worker pods using this query:

```promql
(1300 * (count(max by (label_app_kubernetes_io_name) (kube_pod_labels{label_f5_device_model="i5800"})) or vector(0)) + 500 * (count(max by (label_app_kubernetes_io_name) (kube_pod_labels{label_f5_device_model="5250v"})) or vector(0)))
```

Would it be possible to add an AZ label to these pods?

2023-12-08 14:15 UTC, BenjaminLudwigSAP commented
> Would it be possible to add an AZ label to these pods?
Yes, that should be possible. Have a look in the secrets repo in `*/values/octavia.yaml` at the list under the `workers` key. They have an `availability_zone` sub-key. It just has to be added as a pod label so that Limes can then do filter on it.
I opened #5752 for this.

2023-12-11 13:47 UTC, majewsky approved these changes
This part is good to go. Capacity is discussed in the other PR.

2023-12-19 15:48 UTC, BenjaminLudwigSAP commented
Will merge next year due to current change freeze.

2024-01-08 09:24 UTC, merged