mv pagerduty2slack to schedules2slack
sapcc/helm-charts pull request #5962
Opened 2024-02-02 16:28 UTC by geisslet

2024-02-07 14:57 UTC, IvoGoman requested changes
Besides the dependency version this LGTM

2024-02-07 14:57 UTC, IvoGoman commented on global/schedules2slack/Chart.lock
> +  version: 0.9.3
This version does not exists: https://github.com/sapcc/helm-charts/blob/master/common/owner-info/Chart.yaml
```suggestion
  version: 0.2.3
```

2024-02-07 14:57 UTC, IvoGoman commented on global/schedules2slack/Chart.yaml
> +    version: 0.9.3
```suggestion
    version: 0.2.3
```

2024-02-08 16:21 UTC, geisslet reviewed
thanks!

2024-02-09 16:14 UTC, merged