[Nova] Move credentials into Secret objects
sapcc/helm-charts pull request #6161
Opened 2024-03-14 10:02 UTC by joker-at-work

Please see the individual commits' messages.

2024-03-15 12:34 UTC, joker-at-work commented
Tested in a lab to create a VM, attach a volume, look at its console. migration tasks worked and `nova-bigvm` didn't spew any errors either.

2024-03-18 17:05 UTC, grandchild requested changes

2024-03-18 17:06 UTC, grandchild commented
i can't say that i'm confident that i have understood everything...

2024-03-19 07:43 UTC, joker-at-work commented on openstack/nova/templates/bin/_db-migrate.tpl
> +	EOF
Yes, the whole patch worked for me including the migration task.

Did you maybe replace the tab characters with spaces?

2024-03-19 07:49 UTC, joker-at-work commented
> i can't say that i'm confident that i have understood everything...

any questions that would help in understanding (parts) better?

2024-03-19 09:10 UTC, grandchild commented on openstack/nova/templates/bin/_db-migrate.tpl
> +	EOF
yeah, i did. i did not know the _type_ of whitespace makes this behave differently. 🤯 😨 🤦🏾

2024-03-19 13:42 UTC, grandchild approved these changes

2024-03-26 08:23 UTC, merged