[Keystone] Enable linkerd jobs
sapcc/helm-charts pull request #6460
Opened 2024-04-30 12:39 UTC by rajivmucheli

2024-04-30 13:31 UTC, joker-at-work requested changes
https://github.com/sapcc/helm-charts/blob/8740ab8d1c22b5db71516cce60e61713a1ffd3ec/openstack/keystone/templates/bin/_repair_assignments.tpl#L2 needs changing, too. contains the old proxysql shutdown stuff. I don't think it should contain it as it's run multiple times from the same cron-service-running pod.

2024-04-30 13:31 UTC, joker-at-work commented on openstack/keystone/templates/bin/_db-sync.tpl
> +{{- include "utils.script.job_finished_hook" . | trim }}
Same here. Need to switch `{{-` to `{{`.

2024-04-30 13:38 UTC, joker-at-work approved these changes

2024-04-30 13:46 UTC, bbobrov requested changes
Please add a description to the pull request or to the commit messages describing why this change is necessary and what it does

2024-05-02 11:43 UTC, bbobrov approved these changes

2024-05-02 11:49 UTC, merged