Set deferred_deletion periodic callback value
sapcc/helm-charts pull request #6461
Opened 2024-05-01 08:23 UTC by kpawar-sap

2024-05-06 09:44 UTC, Carthaca requested changes

2024-05-06 09:44 UTC, Carthaca commented on openstack/manila/templates/etc/_manila.conf.tpl
> +periodic_deferred_delete_interval == {{ .Values.periodic_deferred_delete_interval | default 300 }}
```suggestion
periodic_deferred_delete_interval = {{ .Values.periodic_deferred_delete_interval | default 300 }}
```

should be an assignment

2024-05-06 10:16 UTC, Carthaca approved these changes

2024-05-08 07:13 UTC, chuan137 approved these changes

2024-05-08 07:52 UTC, merged