inhibition for some cc3test alerts
sapcc/helm-charts pull request #6570
Opened 2024-05-23 13:46 UTC by artherd42

2024-05-23 13:51 UTC, richardtief approved these changes
Looks good syntactical. Thanks.

2024-05-23 13:51 UTC, richardtief commented on global/prometheus-alertmanager-operated/templates/am-config-inhibit-rules-cc3test.yaml
> +  name: inhibit-rules-keppel
```suggestion
  name: inhibit-rules-cc3test
```

2024-05-23 14:47 UTC, viennaa requested changes
Please bump the _minor_ version of the chart since it is adding a new config.

2024-05-24 07:52 UTC, viennaa approved these changes
Good to go

2024-05-24 07:53 UTC, merged