[keystone]pump up mariadb-galera dependencies
sapcc/helm-charts pull request #6707
Opened 2024-06-19 13:52 UTC by bashar-alkhateeb

pump up dependencies to mariadb-galera 0.27.1
 - add feature to fix persistent volume fs permissions

Change-Id: Ic78187936d14c1c4f7b44f5e590917ea95ea908f

2024-06-19 14:00 UTC, bbobrov reviewed
Should we increase the keystone chart version too?

2024-06-19 14:23 UTC, businessbean approved these changes
lgtm

2024-06-19 14:27 UTC, businessbean requested changes
the keystone chart version has to be bumped to indicate the change

2024-06-19 15:00 UTC, businessbean approved these changes
the keystone chart version bump does not seem to be required...

2024-06-20 06:59 UTC, bashar-alkhateeb commented
AFAIK we dont increase the wrapper helm chart when we pump up the dependencies .. @bbobrov if you think it is better for keystone we can increase the version , i am totally fine with it ?

2024-06-20 10:03 UTC, bbobrov approved these changes

2024-06-20 11:45 UTC, merged