Add option to enable all stable feature flags in RabbitMQ instance
sapcc/helm-charts pull request #6749
Opened 2024-07-02 09:42 UTC by s10

2024-07-03 09:23 UTC, bashar-alkhateeb approved these changes
LGTM!

2024-07-03 09:24 UTC, galkindmitrii reviewed
Please bump the chart version.
I think we'll need a review from @notque and @Carthaca who are using persistence with RabbitMQ.

2024-07-03 09:25 UTC, bashar-alkhateeb requested changes
please increase the version of the Chart and add a section in CHANGELOGS.md to explain tis change

2024-07-03 12:25 UTC, bashar-alkhateeb approved these changes

2024-07-04 09:49 UTC, galkindmitrii approved these changes
I think the chart version 0.7.2 will now collide with other PR: https://github.com/sapcc/helm-charts/pull/6752/files

2024-07-04 10:12 UTC, s10 commented
> I think the chart version 0.7.2 will now collide with other PR: https://github.com/sapcc/helm-charts/pull/6752/files

Unfortunately, a collision happened; there are currently four 0.7.2 PRs. Whichever will be merged first, others will be rebased upon it and change version.

2024-07-08 14:41 UTC, merged