[cronus] Add support for secrets-inejctor resolve for RabbitMQ URIs
sapcc/helm-charts pull request #6958
Opened 2024-08-13 09:46 UTC by s10

…d URI

2024-08-13 11:10 UTC, bashar-alkhateeb requested changes
don't forget the bump up the chart version

2024-08-13 11:10 UTC, bashar-alkhateeb commented on openstack/cronus/templates/nebula/_helpers.tpl
> +        {{"{{"}} resolve "{{ $str }}" {{"}}"}}
don't we need to add `urlquery` escaping here ?

2024-08-13 11:10 UTC, bashar-alkhateeb commented on openstack/cronus/templates/rhea/_helpers.tpl
> +        {{"{{"}} resolve "{{ $str }}" {{"}}"}}
and here ?

2024-08-13 13:30 UTC, bashar-alkhateeb approved these changes
Looks good to me 
@corey-aloia would you check form your end ?

2024-08-29 10:57 UTC, dhalimi1975 approved these changes
Looks okay by me

2024-08-29 15:06 UTC, merged