[Keystone] remove tempest setup
sapcc/helm-charts pull request #7117
Opened 2024-09-24 08:08 UTC by rajivmucheli

The new setup is located at https://github.com/sapcc/helm-charts/tree/master/openstack/tempest/keystone-tempest

2024-09-25 10:07 UTC, rajivmucheli commented
This change was introduced before tempest tests were green. Let's take a step back, merge the previous tempest PR, validate it for few days and look into this PR.

2024-09-25 11:03 UTC, stanislav-zaprudskiy requested changes
Removing references to the deleted template files is also required in [`templates/configmap-etc.yaml`](https://github.com/sapcc/helm-charts/blob/remove_tempest_keystone/openstack/keystone/templates/configmap-etc.yaml) (e.g. `rally_deployment_config.json`)

2024-09-26 10:14 UTC, stanislav-zaprudskiy commented
> @bbobrov shall we remove this spec https://github.com/sapcc/helm-charts/blob/remove_tempest_keystone/openstack/keystone/values.yaml#L190-L198 now that all PR's are merged and working ?

I believe it would be failing during deployments where `.Values.tempest` hash is not provided, e.g. while performing this check here https://github.com/sapcc/helm-charts/blob/remove_tempest_keystone/openstack/keystone/templates/etc/_policy.yaml.tpl#L24.

2024-09-26 10:22 UTC, rajivmucheli commented
> I believe it would be failing during deployments where `.Values.tempest` hash is not provided, e.g. while performing this check here https://github.com/sapcc/helm-charts/blob/remove_tempest_keystone/openstack/keystone/templates/etc/_policy.yaml.tpl#L24.

When i ran it locally it worked and the idea is to control this in secrets (tempest is only enabled in qa).

2024-09-26 10:41 UTC, stanislav-zaprudskiy approved these changes

2024-09-27 09:49 UTC, bbobrov requested changes
This must also have an approval from @misamoylov

2024-09-27 09:49 UTC, bbobrov commented on openstack/keystone/values.yaml
> -  adminProjectId: not_set_in_production
This value is still needed

2024-09-27 09:49 UTC, bbobrov commented on openstack/keystone/values.yaml
> -  domainId: not_set_this_in_production
This value is still needed

2024-10-01 11:14 UTC, rajivmucheli commented on openstack/keystone/values.yaml
> -  adminProjectId: not_set_in_production
this value is enabled in secrets.

2024-10-01 11:14 UTC, rajivmucheli commented on openstack/keystone/values.yaml
> -  domainId: not_set_this_in_production
this value is enabled in secrets.

2024-10-01 11:27 UTC, bbobrov reviewed
This is good, but it still must be approved by @misamoylov

2024-10-01 12:56 UTC, merged