[greenhouse][opentelemetry] add opentelemetry pluginpreset
sapcc/helm-charts pull request #7263
Opened 2024-10-16 12:57 UTC by timojohlo

2024-10-16 13:03 UTC, timojohlo commented
Not sure if we need additional labels e.g. `greenhouse.sap/cluster-presets-enabled: "true"` and if `cluster-type:` is necessary?

2024-10-17 13:56 UTC, IvoGoman requested changes

2024-10-17 13:56 UTC, IvoGoman commented on system/greenhouse-ccloud/templates/opentelemetry-pluginpreset.yaml
> +  password: {{ required ".Values.openTelemetry.openSearchLogs.password missing" $r.openSearchLogs.password | b64enc }}
The required text is misleading maybe ".Values.openTelemetry.clusters[].openSearchLogs.password missing"

2024-10-17 13:56 UTC, IvoGoman commented on system/greenhouse-ccloud/templates/opentelemetry-pluginpreset.yaml
> +  username: {{ required ".Values.openTelemetry.openSearchLogs.username missing" $r.openSearchLogs.username | b64enc }}
The required text is misleading maybe ".Values.openTelemetry.clusters[].openSearchLogs.username missing"

2024-10-17 13:56 UTC, IvoGoman commented on system/greenhouse-ccloud/templates/opentelemetry-pluginpreset.yaml
> +      value: {{ $r.openSearchLogs.password }}
This should be `valueFrom` syntax to refer to the secret created above.

2024-10-17 14:28 UTC, IvoGoman approved these changes

2024-10-17 14:30 UTC, merged