Add kube-monitoring-compute-pluginpreset
sapcc/helm-charts pull request #7307
Opened 2024-10-23 15:08 UTC by max-len

2024-10-24 09:44 UTC, richardtief requested changes
outdated comment.

2024-10-24 12:42 UTC, richardtief requested changes
Solved.

2024-10-24 12:42 UTC, richardtief commented on system/greenhouse-ccloud/templates/kube-monitoring-compute-pluginpreset.yaml
> +  name: kube-monitoring
```suggestion
  name: kube-monitoring-compute
```

2024-10-25 09:31 UTC, auhlig commented
For now, I solved it with the existing `kube-monitoring` pluginpreset. An additional `kube-monitoring-compute` would only be necessary if its configuration significantly deviates from the `kube-monitoring` one

2024-10-25 09:46 UTC, richardtief approved these changes
Updated the PluginPreset accordingly.

2024-10-25 12:58 UTC, merged