[Keystone] support secret-injector
sapcc/helm-charts pull request #7472
Opened 2024-11-27 09:28 UTC by rajivmucheli

With the recent version bump we got a new helper in the `utils` chart that makes it possible to support `secrets-injector` secrets will still maintaining compatibility. This is also required for upcoming PCI audit and secret rotation..

2024-11-27 09:31 UTC, fwiesel approved these changes

2024-11-27 09:36 UTC, galkindmitrii approved these changes

2024-11-27 10:35 UTC, fwiesel requested changes
Anything that is an url needs  `resolve_secret_urlquery` instead of `resolve_secret`

2024-11-27 10:35 UTC, fwiesel commented on openstack/keystone/templates/etc/_secrets.conf.tpl
> +connection = mysql+pymysql://{{ .Values.mariadb_galera.mariadb.users.keystone.username }}:{{.Values.mariadb_galera.mariadb.users.keystone.password | include "resolve_secret" }}@{{include "db_host" .}
That would need to be  `| include "resolve_secret_urlquery" `

2024-11-27 10:35 UTC, fwiesel commented on openstack/keystone/templates/etc/_secrets.conf.tpl
> +connection = mysql+pymysql://{{ default .Release.Name .Values.global.dbUser }}:{{.Values.global.dbPassword | include "resolve_secret" }}@{{include "db_host" .}}/{{ default .Release.Name .Values.maria
That would need to be  `| include "resolve_secret_urlquery" `

2024-11-27 10:35 UTC, fwiesel commented on openstack/keystone/templates/etc/_secrets.conf.tpl
> +connection = mysql+pymysql://{{ .Values.mariadb_galera.mariadb.users.keystone.username }}:{{.Values.mariadb_galera.mariadb.users.keystone.password | include "resolve_secret" }}@{{include "db_host" .}
That would need to be  `| include "resolve_secret_urlquery" `

2024-11-27 10:35 UTC, fwiesel commented on openstack/keystone/templates/etc/_secrets.conf.tpl
> +transport_url = rabbit://{{ .Values.audit.central_service.user }}:{{ .Values.audit.central_service.password | include "resolve_secret" }}@{{ .Values.audit.central_service.host }}:{{ .Values.audit.cen
That would need to be  `| include "resolve_secret_urlquery" `

2024-11-27 10:35 UTC, fwiesel commented on openstack/keystone/templates/etc/_secrets.conf.tpl
> +transport_url = rabbit://{{ .Values.rabbitmq.users.default.user | default "rabbitmq" }}:{{ .Values.rabbitmq.users.default.password | include "resolve_secret" }}@{{ .Values.rabbitmq.host }}:{{ .Values
That would need to be  `| include "resolve_secret_urlquery" `

2024-11-27 10:35 UTC, fwiesel commented on openstack/keystone/templates/etc/_secrets.conf.tpl
> +transport_url = rabbit://{{ .Values.rabbitmq.users.default.user | default "rabbitmq" }}:{{ .Values.rabbitmq.users.default.password | include "resolve_secret" }}@{{ include "rabbitmq_host" . }}:{{ .Va
That would need to be  `| include "resolve_secret_urlquery" `

2024-11-27 10:37 UTC, fwiesel commented on openstack/keystone/templates/etc/_secrets.conf.tpl
> +memcache_password = {{ .Values.memcached.auth.password | include "resolve_secret" }}
Technically, we would also need to escape here a potential `$` sign, but since it wasn't before, it should be fine.

2024-11-27 10:50 UTC, fwiesel approved these changes

2024-11-27 11:26 UTC, s10 commented on openstack/keystone/templates/etc/_secrets.conf.tpl
> +transport_url = rabbit://{{ .Values.audit.central_service.user }}:{{ .Values.audit.central_service.password | include "resolve_secret_urlquery" }}@{{ .Values.audit.central_service.host }}:{{ .Values.
`.Values.audit.central_service.user` here should be with `resolve_secret_urlquery`, because in some places it's taken from the vault.

2024-11-28 08:33 UTC, s10 approved these changes

2025-01-17 10:44 UTC, s10 approved these changes

2025-02-12 13:55 UTC, merged