Updated to receive alerts for CC test channel
sapcc/helm-charts pull request #7499
Opened 2024-12-02 21:49 UTC by himanip94

Added a route and receiver for CC KVM test channel alerts (#alert-kvm-test)

2024-12-03 14:50 UTC, viennaa requested changes
Bump the chart version please.

2024-12-03 21:39 UTC, himanip94 commented
Dumb question but could you please tell me which file are we talking about?

2024-12-06 08:56 UTC, richardtief requested changes
Looks good. A few little things before we can continue.

2024-12-06 08:56 UTC, richardtief commented on global/prometheus-alertmanager-operated/templates/am-config-route-slack.yaml
> +            value: compute
These labels are not used at all. They can be removed. 
```suggestion
```

2024-12-06 08:56 UTC, richardtief commented on global/prometheus-alertmanager-operated/templates/am-config-route-slack.yaml
> +            matchType: "="
Regex matches require a different `matchType`.
```suggestion
            matchType: "=~"
```

2024-12-06 08:57 UTC, richardtief commented
Yes, exactly.
> Dumb question but could you please tell me which file are we talking about? https://github.com/sapcc/helm-charts/blob/master/global/prometheus-alertmanager-operated/Chart.yaml#L5 - Bumping this to 4.5.2?

2024-12-09 09:13 UTC, merged