liquid-ceph: add support for per-az usage and quota
sapcc/helm-charts pull request #7507
Opened 2024-12-05 09:15 UTC by jecluis

Signed-off-by: Joao Eduardo Luis \<joao@clyso.com>

2024-12-05 09:45 UTC, Nuckal777 requested changes

2024-12-05 09:45 UTC, Nuckal777 commented on system/liquid-ceph/templates/configmap.yaml
> +  zone-mapping.yaml: ""
I think the value here needs to be templated.

2024-12-05 09:45 UTC, Nuckal777 commented on system/liquid-ceph/templates/deployment.yaml
> +            name: zone-mapping
I think the mount points collide. I would propose to move `zone-mappings.yaml` and `policies.yaml` in a single ConfigMap (e.g. called just `liquid-ceph`). Then mounting that single ConfigMap would provide both files.

2024-12-05 09:47 UTC, majewsky requested changes

2024-12-05 09:47 UTC, majewsky commented on system/liquid-ceph/templates/configmap.yaml
> +  zone-mapping.yaml: ""
Why do you try to make the configmap name the thing that is configured? The standard approach is to take the zoneMapping config itself via `values.yaml` and render it out here (Ctrl-F `toYaml` on this repo for many many examples of how to do this). Then hardcode the configMap name at the usage site.

2024-12-05 15:52 UTC, databus23 commented on system/liquid-ceph/templates/configmap.yaml
> +  zone-mapping.yaml: ""
To directly specify the yaml in the values file and render it out here I think this should do it.
```suggestion
  zone-mapping.yaml: | {{- toYaml .Values.ceph.zoneMapping | nindent 4 }}
```

2024-12-05 16:06 UTC, databus23 commented on system/liquid-ceph/values.yaml
> +  zoneMapping: "" # zone mapping file
file is misleading there needs to be yaml there
```suggestion
  zoneMapping: {} # zone mapping yaml
```

2024-12-05 16:07 UTC, databus23 commented on system/liquid-ceph/ci/test-values.yaml
> +  zoneMapping: zone-mapping
```suggestion
  zoneMapping:
    az-a-3:
      resource: local-standard
      az: a
```

2024-12-09 08:36 UTC, Nuckal777 commented on system/liquid-ceph/templates/deployment.yaml
> +          {{ .Values.ceph.enableDebug }}
Missing `if`.

2024-12-12 07:49 UTC, databus23 commented on system/liquid-ceph/templates/deployment.yaml
> +          {{ if .Values.ceph.enableDebug }}
```suggestion
          {{- if .Values.ceph.enableDebug }}
```

2024-12-12 07:49 UTC, databus23 commented on system/liquid-ceph/templates/deployment.yaml
> +          {{ end }}
```suggestion
          {{- end }}
```

2024-12-12 07:50 UTC, databus23 approved these changes

2024-12-12 13:37 UTC, kayrus commented on system/liquid-ceph/ci/test-values.yaml
> +    az-a-3:
can we reuse the `rgwTargetPlacements` and `premiumPlacements` mappings from the system/cc-ceph chart? duplicating zone mappings adds flexibility, but also a complexity and a room for a human error.

2024-12-12 13:37 UTC, kayrus commented on system/liquid-ceph/ci/test-values.yaml
> +    az-a-3:
cc @sumitarora2786

2024-12-12 14:18 UTC, databus23 approved these changes

2024-12-13 08:32 UTC, merged